-- EMP TABLOSUNDAKÝ KAYITLARDAN EMPNO'SU EN BÜYÜK OLANI EKRANA YAZALIM
-- DEPT TABLOSUNDAN DA DNAME ALANINI ÝKÝNCÝ BÝR SORGUYLA ALIP ÇIKTIYA YAZDIRALIM

DECLARE
    p_EMPNO EMP.EMPNO%TYPE;
    p_ENAME EMP.ENAME%TYPE;
    p_SAL EMP.SAL%TYPE;
    p_DEPTNO EMP.DEPTNO%TYPE;
    p_DNAME DEPT.DNAME%TYPE;
BEGIN
    SELECT EMPNO, ENAME, SAL, DEPTNO INTO p_EMPNO, p_ENAME, p_SAL, p_DEPTNO 
    FROM EMP WHERE EMPNO = (SELECT MAX(EMPNO) FROM EMP);
    
    SELECT DNAME INTO p_DNAME FROM DEPT WHERE DEPTNO = P_DEPTNO;
    
    DBMS_OUTPUT.PUT_LINE('EMPNO = ' || p_EMPNO);
    DBMS_OUTPUT.PUT_LINE('ENAME = ' || p_ENAME);
    DBMS_OUTPUT.PUT_LINE('SAL = ' || p_SAL);
    DBMS_OUTPUT.PUT_LINE('DEPTNO = ' || p_DEPTNO);
    DBMS_OUTPUT.PUT_LINE('DNAME = ' || p_DNAME);
END;