declare
    TARIH VARCHAR2(50);
    YIL VARCHAR2(50);
    AY VARCHAR2(50);
    GUN VARCHAR2(50);
    SAAT VARCHAR2(50);
    DAKIKA VARCHAR2(50);
    SANIYE VARCHAR2(50);
begin
    TARIH := TO_CHAR(CURRENT_DATE, 'DD/MM/YYYY HH24:MI:SS'); -- CURRENT_DATE => DB SAATÝNÝ ALI, SYSDATE => BÝLGÝSAYARIN SAATÝNÝ ALIR
    YIL := TO_CHAR(SYSDATE, 'YYYY');
    AY := TO_CHAR(SYSDATE, 'MM'); -- MON => DEC
    GUN := TO_CHAR(SYSDATE, 'DD'); -- DAY => SUNDAY
    SAAT := TO_CHAR(SYSDATE, 'HH24');
    DAKIKA := TO_CHAR(SYSDATE, 'MI');
    SANIYE := TO_CHAR(SYSDATE, 'SS');
    
    DBMS_OUTPUT.PUT_LINE('TARIH = ' || TARIH);
    
    DBMS_OUTPUT.PUT_LINE('YIL = ' || YIL);
    DBMS_OUTPUT.PUT_LINE('AY = ' || AY);
    
    DBMS_OUTPUT.PUT_LINE('GUN = ' || GUN);
    DBMS_OUTPUT.PUT_LINE('SAAT = ' || SAAT);
    DBMS_OUTPUT.PUT_LINE('DAKIKA = ' || DAKIKA);
    DBMS_OUTPUT.PUT_LINE('SANIYE = ' || SANIYE);
end;